services:
  bentopdf:
    # GitHub Container Registry (Recommended)
    # Self-Hosted build - ghcr.io/alam00000/bentopdf-simple:latest
    # Commercial build  - ghcr.io/alam00000/bentopdf:latest
    # Docker Hub (Alternative)
    # Self-Hosted build - bentopdfteam/bentopdf-simple:latest
    # Commercial build  - bentopdfteam/bentopdf:latest
    build:
      context: .
      args:
        SIMPLE_MODE: "true"
        VITE_BRAND_NAME: "OIL PDF Tools"
        VITE_BRAND_LOGO: "images/new-logo.png"
        VITE_FOOTER_TEXT: "Powered BentoPDF. Internal use only. Source Code: github.com/Prabah-Kalita/BentoPDF-Implementationy"
    image: bentopdf-simple:latest
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - '127.0.0.1:1795:8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
